### PR TITLE
adding action

### PR DESCRIPTION
**Pull request by admiralAwkbar**
- Adding code to make this a full GitHub Action

### CODE REVIEW

**Comment by Link-** [comment]
@admiralAwkbar amazing, can we add details for how to use this in a workflow in the README?

**Comment by admiralAwkbar** [comment]
Yes sir! Working on the jwt install... It's being angry

**Comment by Link-** [comment]
Opps this is still a draft sorry! Thank you very much for your hard work 🙇‍♂️

**Comment by admiralAwkbar** [comment]
@Link- I was able to get the image up and running using Ubuntu instead of Apline.. seems a missing lib or something

Now when I try to generate a token, I'm getting an odd failure... Can you try to reproduce?

`docker build -t github/gh-token:latest -f Dockerfile .`

After that, you can run:

`docker run -it --entrypoint /bin/bash github/gh-token:latest`

All you need to do now:
- copy a key.pem to the root folder
- `gh-tokengenerate --key key.pem --app_id SOME_ID --duration 10 --hostname api.github.com`

From there I'm getting a bad curl response...

**Review by Tied2eth — DISMISSED** [review]

**Comment by Link-** [comment]
> @Link- I was able to get the image up and running using Ubuntu instead of Apline.. seems a missing lib or something
> 
> Now when I try to generate a token, I'm getting an odd failure... Can you try to reproduce?
> 
> `docker build -t github/gh-token:latest -f Dockerfile .`
> 
> After that, you can run:
> 
> `docker run -it --entrypoint /bin/bash github/gh-token:latest`
> 
> All you need to do now:
> 
> * copy a key.pem to the root folder
> * `gh-token generate --key key.pem --app_id SOME_ID --duration 10 --hostname api.github.com`
> 
> From there I'm getting a bad curl response...

I'm not even getting to the point of being able to test, I have a weird error while building the container:

```
=> CACHED [5/6] COPY .automation/run-gh-token.sh ./                                                        0.0s
 => ERROR [6/6] RUN curl -sL https://github.com/mike-engel/jwt-cli/releases/download/4.0.0/jwt-linux.tar.g  0.8s
------
 > [6/6] RUN curl -sL https://github.com/mike-engel/jwt-cli/releases/download/4.0.0/jwt-linux.tar.gz --output ./jwt-linux.tar.gz     && tar xvfz jwt-linux.tar.gz:
------
executor failed running [/bin/sh -c curl -sL https://github.com/mike-engel/jwt-cli/releases/download/4.0.0/jwt-linux.tar.gz --output ./jwt-linux.tar.gz     && tar xvfz jwt-linux.tar.gz]: exit code: 77
```

Also a few of things that might make your life easier:

1. `--hostname api.github.com` is not really required if you're using .com it's only needed for GHES
2. `--duration` is only for the JWT not for the installation access token

**Review by stebje — DISMISSED** [review]

**Review by gusshawstewart — DISMISSED** [review]

**Comment by admiralAwkbar** [comment]
@Link- i think i got this done... now we just need to cut a release and validte
then we should be golden...

**Comment by Link-** [comment]
@admiralAwkbar brilliant sir! I'll carve out some time this week to review and merge!

**Comment by Link-** [comment]
FYI - I found a bug.

```
build
link-/gh-token/action/action.yml (Line: 17, Col: 18): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.PRIVATE_KEY
```

It seems that if we use `${{ secrets.... }}` in the `action.yml` actions will fail like this:
9FDC8877-E29C-45D1-BF2E-D8B7D6217F1A
1C7B729B-448C-4E76-93E0-BB7AE01AF4E4

**Comment by Link-** [comment]
@admiralAwkbar  I'm facing hurdles testing this, I guess we're not really ready to ship it yet:
39A9505A-848C-4E28-8FA9-DF7C579F2DC6

**Comment by Link-** [comment]
@admiralAwkbar I fixed all the issues, I think this definitely requires more testing and specifically:
1. Installation IDs fetching
2. Token revoke testing

I also made some changes to the README.

Lastly, if we're going to have this available as an action then we need to maintain a Docker image and releases. Do you happen to have a workflow that will generate those? Shall we add it to this PR? 

I'm fine with merging this right away after testing and we can work on the releases leater.

Lastly, thank you for all the hard work here <3

**Pull request closed without merging**
